version: '3.2'

services:
  server: # POSM Auth Server
    image: "docker.pkg.github.com/posm/posm-auth/server:${PA_BRANCH_NAME:-master}"
    build:
      context: .
      cache_from:
        - "docker.pkg.github.com/posm/posm-auth/server:${PA_BRANCH_NAME}"
        - docker.pkg.github.com/posm/posm-auth/server:master
    environment:
      - POSM_ADMIN_URL=http://localhost:8051/posm/
      - COOKIE_DOMAIN=.posm.io
    command: /code/scripts/run_develop.sh
    volumes:
      - ./:/code
    ports:
      - '8050:8050'

  nginx: # NGINX Dummy Server
    image: nginx:1.13
    volumes:
      - ./posm-nginx/:/etc/nginx/conf.d/:z
    ports:
      - '8051:80'
    depends_on:
      - server
