version: '3.2'

services:
  server: # POSM Auth Server
    image: "docker.pkg.github.com/posm/posm-auth:${PA_BRANCH_NAME:-master}"
    build:
      context: .
      cache_from:
        - "docker.pkg.github.com/posm/posm-auth:${PA_BRANCH_NAME}"
        - docker.pkg.github.com/posm/posm-auth:master
    environment:
      # For supporting subpath in Django
      - FORCE_SCRIPT_NAME=/admin-panel
    command: /code/scripts/run_develop.sh
    volumes:
      - ./:/code

  nginx: # NGINX Dummy Server
    image: nginx:1.13
    volumes:
      - ./posm-nginx/:/etc/nginx/conf.d/:z
      - ./static/:/server-static/:z
      - ./media/:/server-media/:z
    ports:
      - '8005:80'
    depends_on:
      - server
