# Generated by Django 2.2.6 on 2019-10-31 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosmComponentPermission',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('http_method', models.CharField(choices=[('safe', 'Safe'), ('unsafe', 'Unsafe')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(to='group.PosmComponentPermission')),
            ],
        ),
    ]
