# Generated by Django 2.2.6 on 2019-10-31 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posmcomponentpermission',
            old_name='title',
            new_name='url_pattern',
        ),
        migrations.RemoveField(
            model_name='posmcomponentpermission',
            name='http_method',
        ),
    ]
