# Generated by Django 2.2.6 on 2019-10-31 04:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_userpermissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPermissions',
            new_name='Profile',
        ),
    ]
